version: '3.2'
services:
    PostgreSQL:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=postgres
          - POSTGRES_DB=postgres
      ports:
           - "5442:5442"

    Order_System:
       image: 'payment_image'
       depends_on:
           - PostgreSQL
       ports:
           - "8079:8079"
       environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5442/postgres
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=password
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
          